# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
