# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djreact', '0002_auto_20170424_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='entity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreact.Entity'),
        ),
    ]
